copyright = "© Asjad Naqvi"
defaultContentLanguage = "en"
disableKinds = ["taxonomy"]
enableRobotsTXT = true
languageCode = "en"
timeZone = "Europe/Berlin"
timeout = "120s"
title = "StataViz Portfolio"

[params]
  defaultTheme = "dark"
  description = ""
  title = "StataViz Portfolio"
  [params.author]
    email = "asjadnaqvi@gmail.com"
    name = "Asjad Naqvi"
  [params.socialIcons]
    #facebook = "https://www.facebook.com/"
    #instagram = "https://www.instagram.com/"
    github = "https://github.com/asjadnaqvi/"
    #youtube = "https://www.youtube.com/"
    website = "https://asjadnaqvi.github.com"
    twitter = "https://x.com/AsjadNaqvi"
	bluesky = "https://bsky.app/profile/asjadnaqvi.bsky.social"
	linkedin = "https://www.linkedin.com/in/asjadnaqvi/"
	#mastodon = "https://example.com"
    #pixelfed = "https://example.com"

[outputs]
  home = ["HTML", "RSS"]
  page = ["HTML"]
  section = ["HTML"]

[imaging]
  quality = 75
  resampleFilter = "CatmullRom"
  [imaging.exif]
    disableDate = false
    disableLatLong = true
    includeFields = "ImageDescription|Orientation"

[module]
  [module.hugoVersion]
    min = "0.121.2"
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"

[menu]
  [[menu.footer]]
    name = "GitHub"
    url = "https://github.com/asjadnaqvi/"
    weight = 3

[services]
  [services.rss]
    limit = 100

[related]
  includeNewer = true
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'keywords'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 50